# Generated by Django 3.1.7 on 2021-03-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=191, unique=True, verbose_name='Email'),
        ),
        migrations.AlterUniqueTogether(
            name='customerproduct',
            unique_together={('customer', 'product')},
        ),
    ]
