# Generated by Django 3.1.7 on 2021-03-23 00:54

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210322_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='price',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(
                default=timezone.now(), verbose_name='Date'),
            preserve_default=False,
        ),
    ]
